name: 拉取镜像推送

on:
  workflow_dispatch:
    inputs:
      IMAGES_FILE:
        description: '镜像列表文件路径'
        required: true
        default: 'images.txt'
      TARGET_REGISTRY:
        description: '仓库地址'
        required: true
        default: 'registry.cn-guangzhou.aliyuncs.com'
      TARGET_REPOSITORY:
        description: '空间名称'
        required: true
        default: 'kubesphere_wen'
      ARCH:
        description: '系统架构'
        required: true
        default: 'amd64'
        type: choice
        options:
          - amd64
          - arm64
          - arm/v7
          - arm/v6
          - "386"
          - s390x
          - ppc64le

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码库
        uses: actions/checkout@v2

      - name: 读取镜像列表文件
        id: read_images
        run: |
          images=$(cat ${{ github.event.inputs.IMAGES_FILE }} | tr '\n' ' ')
          echo "Images: $images"
          echo "images=$images" >> $GITHUB_ENV

      - name: 登录到 Docker 仓库
        id: login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} ${{ github.event.inputs.TARGET_REGISTRY }}
        continue-on-error: true

      - name: 检查 Docker 登录成功
        if: ${{ steps.login.outcome == 'success' }}
        run: echo "Docker 登录成功"

      - name: 检查 Docker 登录失败
        if: ${{ steps.login.outcome != 'success' }}
        run: echo "Docker 登录失败"

      - name: 拉取、标记并推送 Docker 镜像
        id: pull_tag_push
        run: |
          for image in ${{ env.images }}; do

            original_image=$(echo $image | cut -d':' -f1)
            tag=$(echo $image | cut -d':' -f2)

            base_image=$(basename $original_image)

            new_image="${{ github.event.inputs.TARGET_REGISTRY }}/${{ github.event.inputs.TARGET_REPOSITORY }}/$base_image:$tag"

            docker pull --platform ${{ github.event.inputs.ARCH }} $original_image:$tag
            docker tag $original_image:$tag $new_image
            docker push $new_image
          done
        continue-on-error: true

      - name: 检查镜像推送成功
        if: ${{ steps.pull_tag_push.outcome == 'success' }}
        run: echo "Docker 镜像推送成功"

      - name: 检查镜像推送失败
        if: ${{ steps.pull_tag_push.outcome != 'success' }}
        run: echo "Docker 镜像推送失败"